/* formal definition of GCSE spec in W3C EBNF */

// space or tab or LF or CR
ws ::= " " | #x9 | #xA | #xD
// optional CR then LF
eol ::= #xD? #xA

digit_excluding_zero ::= [0-9]
digit ::= digit_excluding_zero | "0"


integer ::= "-"? digit_excluding_zero digit*
float ::= "-"? digit+ "." digit+

comparison_operator ::= [!=] "=" | [<>] "="?
boolean_operator ::= "AND" | "OR" | "NOT"

identifier ::= [a-zA-Z] [a-zA-Z0-9]*

// function_name(param_one, param_two)
function_call ::= identifier "(" (expression ",")* expression ")"
