/* formal definition of specs in W3C EBNF */
/* sections in @as{} are only available in AS or greater, likewise @a2{} */

/* space or tab or LF or CR */
ws ::= (" " | #x9 | #xA | #xD)*
/* optional CR then LF */
eol ::= #xD? #xA

digit_excluding_zero ::= [0-9]
digit ::= digit_excluding_zero | "0"


integer ::= "-"? digit_excluding_zero digit*
integer_ge_zero ::= digit_excluding_zero digit*
float ::= "-"? digit+ "." digit+

comparison_operator ::= [!=] "=" | [<>] "="?
boolean_operator ::= "AND" | "OR" | "NOT"

identifier ::= [a-zA-Z] [a-zA-Z0-9]*

array_def ::= "array" ws identifier ws "[" ws integer_ge_zero (ws "," ws integer_ge_zero)? ws "]"

/* function_name((param_one,)* param_two) */
function_call ::= identifier ws "(" ws (expression ws "," ws)* ws expression ws ")"

/* function and procedure definitions */
function_param ::= identifier ws @as{ (":" ws "by" "val" | "ref")? }
function_def ::= "function" ws identifier ws "(" ws (function_param ws "," ws)* ws function_param ")"
procedure_def ::= "procedure" ws identifier ws "(" ws (function_param ws "," ws)* ws function_param ")"

/* classes */
@a2 {
    access_modifier ::= "public" | "private"
    class_variable_def ::= access_modifier? variable_def
    class_function_def ::= access_modifier? function_def
    class_procedure_def ::= access_modifier? procedure_def
    class_def ::= "class" identifier eol ws (ws class_variable_def | class_function_def | class_procedure_def ws) ws eol "endclass"
}
