[package]
name = "lang_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
serde = { version = "1.0.147", features = ["derive"] }

[dev-dependencies]
ron = "0.8.0"
paste = "1.0.9"
